"""link tasks to subscribers

Revision ID: 006d5495dba6
Revises: 561299fa7c1c
Create Date: 2025-05-30 18:33:17.072845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006d5495dba6'
down_revision: Union[str, None] = '561299fa7c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('contract_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tasks_contract_number'), 'tasks', ['contract_number'], unique=False)
    op.create_foreign_key(None, 'tasks', 'subscribers', ['contract_number'], ['contract_number'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_contract_number'), table_name='tasks')
    op.drop_column('tasks', 'contract_number')
    # ### end Alembic commands ###
