"""create subscribers table

Revision ID: 561299fa7c1c
Revises: a20c60cba80d
Create Date: 2025-05-29 20:50:48.379299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '561299fa7c1c'
down_revision: Union[str, None] = 'a20c60cba80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('contract_number', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('house', sa.String(length=50), nullable=False),
    sa.Column('latitude', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('longitude', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('yandex_address', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='subscriber_status'), server_default='active', nullable=False),
    sa.PrimaryKeyConstraint('contract_number')
    )
    op.create_index(op.f('ix_subscribers_contract_number'), 'subscribers', ['contract_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscribers_contract_number'), table_name='subscribers')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
