"""обавлена таблица executor_work_times

Revision ID: a3575e259c21
Revises: ca13bd2027f6
Create Date: 2025-06-01 13:39:57.286053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3575e259c21'
down_revision: Union[str, None] = 'ca13bd2027f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor_work_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exec_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('work_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exec_id'], ['executors.exec_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executor_work_times_exec_id'), 'executor_work_times', ['exec_id'], unique=False)
    op.create_index(op.f('ix_executor_work_times_id'), 'executor_work_times', ['id'], unique=False)
    op.create_index(op.f('ix_executor_work_times_work_date'), 'executor_work_times', ['work_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executor_work_times_work_date'), table_name='executor_work_times')
    op.drop_index(op.f('ix_executor_work_times_id'), table_name='executor_work_times')
    op.drop_index(op.f('ix_executor_work_times_exec_id'), table_name='executor_work_times')
    op.drop_table('executor_work_times')
    # ### end Alembic commands ###
