"""Make subscriber.surname/name/street nullable

Revision ID: ca13bd2027f6
Revises: 006d5495dba6
Create Date: 2025-06-01 10:54:38.588514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ca13bd2027f6'
down_revision: Union[str, None] = '006d5495dba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'surname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('subscribers', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('subscribers', 'street',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscribers', 'street',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('subscribers', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('subscribers', 'surname',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
